# -*- coding: UTF-8 -*-
import os


DATA_FOLDER_NAME = 'data'
DETAILED_LEDGER_FILENAME = r'107年方殷營業支出.xlsx'
DATA_FOLDER_FULL_PATH = os.path.join(os.getcwd(), DATA_FOLDER_NAME)
DETAILED_LEDGER_FULL_PATH = os.path.join(DATA_FOLDER_FULL_PATH, DETAILED_LEDGER_FILENAME)